### PR TITLE
Edit participation

### PR DESCRIPTION
**Pull request by pbochis**
- improve style for challenge info page
- refacor code on challenge info page
- add button to unregister from challenge
- fix challenge register page to also accept edits

### CODE REVIEW

**Comment by pbochis** [comment]
Some ss's with new styling 
http://prntscr.com/bmpuyr
http://prntscr.com/bmpvaj
http://prntscr.com/bmpvr6
http://prntscr.com/bmpw14
http://prntscr.com/bmpwla

**Comment by lorenzleutgeb** [comment]
Nice screenshots, but none that actually show any editing of for example team and/or location. Why?

**Comment by pbochis** [comment]
Because i reused the `challenge-register-wizard`. It was made by design to also handle edits, i just modified it a bit to prefill the dropdown with already selected values.

**Comment by lorenzleutgeb** [comment]
Makes sense.

**Comment by pbochis** [comment]
@flowlo so does it LGTY?

**Pull request merged**
